content:
  - name: writing
    label: 'Writing Projects'
    type: collection
    path: 'src/content/writing'
    create: true
    slug: '{{slug}}'
    fields:
      - name: title
        label: 'Title'
        type: string
        required: true
      - name: publication
        label: 'Publication'
        type: string
        required: true
      - name: startDate
        label: 'Start Date'
        type: datetime
        required: true
      - name: url
        label: 'URL'
        type: string
        required: false
      - name: body
        label: 'Content'
        type: richtext
        required: true
  - name: editing
    label: 'Editing Roles'
    type: collection
    path: 'src/content/editing'
    create: true
    slug: '{{slug}}'
    fields:
      - name: role
        label: 'Role'
        type: string
        required: true
      - name: publication
        label: 'Publication'
        type: string
        required: true
      - name: startDate
        label: 'Start Date'
        type: datetime
        required: true
      - name: endDate
        label: 'End Date'
        type: datetime
        required: false
      - name: url
        label: 'URL'
        type: string
        required: false
      - name: body
        label: 'Content'
        type: richtext
        required: true
  - name: commercial
    label: 'Commercial Projects'
    type: collection
    path: 'src/content/commercial'
    create: true
    slug: '{{slug}}'
    fields:
      - name: title
        label: 'Title'
        type: string
        required: true
      - name: brand
        label: 'Brand'
        type: string
        required: true
      - name: startDate
        label: 'Start Date'
        type: datetime
        required: true
      - name: url
        label: 'URL'
        type: string
        required: false
      - name: body
        label: 'Content'
        type: richtext
        required: true
  - name: home
    label: "Home Page"
    type: page
    path: src/content/pages/about
    create: false
    fields:
      - name: body
        label: "Content"
        type: richtext
        required: false