content:
  - name: writing
    label: 'Writing Projects'
    type: collection
    path: 'src/content/writing'
    create: true
    slug: '{{slug}}'
    fields:
      - name: title
        label: 'Title'
        type: string
        required: true
      - name: publication
        label: 'Publication'
        type: string
        required: true
      - name: startDate
        label: 'Start Date'
        type: date
        required: true
      - name: url
        label: 'URL'
        type: string
        required: false
      - name: body
        label: 'Content'
        type: rich-text
        required: true
  - name: editing
    label: 'Editing Roles'
    type: collection
    path: 'src/content/editing'
    create: true
    slug: '{{slug}}'
    fields:
      - name: role
        label: 'Role'
        type: string
        required: true
      - name: publication
        label: 'Publication'
        type: string
        required: true
      - name: startDate
        label: 'Start Date'
        type: date
        required: true
      - name: endDate
        label: 'End Date'
        type: date
        required: false
      - name: url
        label: 'URL'
        type: string
        required: false
      - name: body
        label: 'Content'
        type: rich-text
        required: true
  - name: commercial
    label: 'Commercial Projects'
    type: collection
    path: 'src/content/commercial'
    create: true
    slug: '{{slug}}'
    fields:
      - name: title
        label: 'Title'
        type: string
        required: true
      - name: brand
        label: 'Brand'
        type: string
        required: true
      - name: startDate
        label: 'Start Date'
        type: date
        required: true
      - name: url
        label: 'URL'
        type: string
        required: false
      - name: body
        label: 'Content'
        type: rich-text
        required: true
  - name: about
    label: 'About me'
    type: file
    path: 'src/content/pages/about.md'
    fields:
      - name: body
        label: 'Content'
        type: rich-text
        required: true
  - name: site-settings
    label: 'Site settings'
    type: file
    path: 'src/config.ts'
    format: json
settings:
  hide: true
