title: George Alfred Upton
description:
url: https://georgealfredupton.com
author:
  name: George Alfred Upton
  email:
  instagram: gaupton
social:
  name: George Alfred Upton
  links:
    - https://www.instagram.com/gaupton
lang: en_GB
permalink: "/:title/"
markdown: kramdown

kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections

collections:
  commercial:
    output: true
    permalink: /:collection/:name
  editing:
    output: false
  writing:
    output: true

defaults:
  - scope:
      path: ""
      type: "commercial"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "editing"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "writing"
    values:
      layout: "page"
